# Generated by Django 6.0.2 on 2026-02-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='pago_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
