# Generated by Django 6.0.2 on 2026-02-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
