# Generated by Django 6.0.2 on 2026-02-09 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome do serviço')),
                ('descricao', models.TextField(verbose_name='Descrição do serviço')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Preço do serviço')),
                ('duracao_minutos', models.IntegerField(verbose_name='Duração em minutos')),
                ('esta_ativo', models.BooleanField(verbose_name='Esse serviço está ativo?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
