# Generated by Django 6.0.2 on 2026-02-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='esta_ativo',
            field=models.BooleanField(default=True, verbose_name='Esse serviço está ativo?'),
        ),
    ]
