# Generated by Django 6.0.2 on 2026-02-09 01:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options_alter_cliente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(10, message='O telefone deve ter 10 ou 11 dígitos.'), django.core.validators.MaxLengthValidator(11, message='O telefone deve ter 10 ou 11 dígitos.')]),
        ),
    ]
